# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rear', '0002_auto_20160804_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='number',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='state',
            field=models.BooleanField(verbose_name=''),
        ),
    ]
