# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-17 02:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rear', '0004_auto_20160809_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='number',
        ),
    ]
