# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-15 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rear', '0004_auto_20160809_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='query',
            field=models.TextField(default='None', verbose_name='Content'),
        ),
    ]
