# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-15 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rear', '0005_todo_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(verbose_name='Content')),
            ],
        ),
        migrations.RemoveField(
            model_name='todo',
            name='query',
        ),
    ]
